volumes:
  test-database-data:

networks:
  integration-stack:
    name: integration-stack
    external: false

services:
  # Integration Test Database
  test-database:
    container_name: test-database
    image: postgres
    restart: always
    volumes:
      - test-database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - integration-stack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  test-runner:
    image: mcr.microsoft.com/playwright:v1.50.1-jammy
    container_name: test-runner
    depends_on:
      - test-database
    volumes:
      - ./tests:/tests  # Ensure tests folder is mounted properly
    working_dir: /tests  # Ensure correct working directory
    command: [ "sh", "-c", "ls -la /tests && npm install && npx playwright install-deps && npm test" ]
    networks:
      - integration-stack

  web:
    container_name: web
    image: calcom.docker.scarf.sh/calcom/cal.com
    depends_on:
      - test-database
    env_file: .env
    networks:
      - integration-stack
    volumes:
      - .:/app  # Ensure app code is mounted
    working_dir: /app
    command: [ "sh", "-c", "yarn start" ]
