name: Integration Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: ls -la tests/

      - name: Debug Inside Docker
        run: docker compose -f docker-compose.integration.yml run test-runner sh -c "ls -la /tests"

      - name: Start Services (Database & WireMock)
        run: docker compose -f docker-compose.integration.yml up -d test-database wiremock

      - name: Wait for Database & WireMock to be Ready
        run: sleep 10  # Ensures services are fully initialized

      - name: Run Integration Tests
        run: docker compose -f docker-compose.integration.yml up --abort-on-container-exit test-runner

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.integration.yml down --remove-orphans
